language: python

sudo: required
dist: bionic

addons:
  apt:
    packages:
    - git
    - build-essential
    - automake
    - libtool
    - python-dev
    - gettext
    - swig

python:
  - "2.7"

git:
  depth: 1

script:
- echo compiling OverlayHD skin
- python -m compileall .
- find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
- echo done!
